apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "beleva-stack.name" . }}-mysql
  labels:
    {{- include "beleva-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "beleva-stack.name" . }}-media
  labels:
    {{- include "beleva-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.mediaSize }}
