# Generated by Django 5.2 on 2025-07-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='ratings',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='reviews',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
