apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beleva-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/saarvi35/horizon.git'
    targetRevision: main
    path: helm/beleva-stack
    helm:
      releaseName: beleva
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: horizon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
