apiVersion: v1
kind: ConfigMap
metadata:
  name: horizon-config
  namespace: horizon
data:
  DEBUG: "0"
  ALLOWED_HOSTS: "*"
  DB_ENGINE: "django.db.backends.mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "beleva"
  MYSQL_DATABASE: "beleva"