apiVersion: v1
kind: Secret
metadata:
  name: horizon-secret
  namespace: horizon
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-its-=s&um%)ah#33%+5-$xd&c+)4*ltuecg#!55*+j%^blq32q"
  DB_USER: "horizon_user"
  DB_PASSWORD: "BelevaDB@12345"
  MYSQL_ROOT_PASSWORD: "horizon_password"